Spring security session + jwt를 이용한 회원가입, 로그인 기능
f-lab-edu/order66 pull request #2
Opened 2023-10-31 11:12 UTC by herryboro

-  #1 관련 pr입니다.

2023-11-05 21:35 UTC, f-lab-jason requested changes
service나 controller관련된 테스트 코드들도 추가해주시겠어요?

2023-11-05 21:35 UTC, f-lab-jason commented on src/main/java/com/herryboro/order66/controller/ClientMemberController.java
> +    public ResponseEntity<String> mainHome() {
이 `/home`의 용도는 단순 테스트인가요?

2023-11-05 21:35 UTC, f-lab-jason commented on src/main/java/com/herryboro/order66/controller/ClientMemberController.java
>          }
`result에 에러가 있으면 error 필드 내용을 ClientInputDataException으로 wrapping해서 던진다`는 로직이 굉장히 여러 군데서 쓰이는데 util 클래스 같은걸로 하나 빼는게 어떨까요?

2023-11-05 21:35 UTC, f-lab-jason commented on src/main/java/com/herryboro/order66/controller/ClientMemberController.java
> +    @ExceptionHandler({ClientInputDataException.class})
`ExceptionHandler`는 보통 개별 클래스로 빼는 형태를 많이 써요. 여기가 아니라 다른데서도 `ClientInputDataException`을 던질 수 있을텐데 어차피 처리하는건 비슷한 경우가 많으니까요.

2023-11-05 21:35 UTC, f-lab-jason commented on src/main/java/com/herryboro/order66/controller/ClientMemberController.java
> +@RequestMapping(value = "/client")
Rest API를 따른다고 보는데 스펙에 맞게 URL 이름을 조금 변경하면 좋을 것 같아요. Rest API URL 규칙을 한 번 보시면 좋을 것 같습니다.

회원가입: POST method `/clients`
회원수정: PATCH method `/clients`

2023-11-05 21:35 UTC, f-lab-jason commented on src/main/java/com/herryboro/order66/controller/JwtAuthenticationController.java
> +        System.out.println("jwt = " + jwt);
`System.out.println`들은 production 코드에선 제외해주세요

2023-11-05 21:35 UTC, f-lab-jason commented on src/main/java/com/herryboro/order66/exception/ClientInputDataException.java
> +public class ClientInputDataException extends RuntimeException {
nit: 이름이 좀 모호한데 `InvalidInputException`같은걸로 모든 잘못된 사용자 입력을 처리하는게 어떨까요?

2023-11-05 21:35 UTC, f-lab-jason commented on src/main/java/com/herryboro/order66/exception/ClientRegistrationException.java
> +public class ClientRegistrationException extends RuntimeException {
nit: 이것도 조금 더 명확한 이름이면 좋겠어요. 용도를 봐선 중복가입인경우인것 같은데 그에 맞는 이름이면 더 좋겠습니다.

2023-11-05 21:35 UTC, f-lab-jason commented on src/main/java/com/herryboro/order66/security/AuthProvider.java
> +        else errorMsseage = "비밀번호가 일치하지 않습니다.";
nit: checkstyle 같은 코드 스타일링 툴을 쓰시는게 어떨까요?
```
        if (userDto != null && passwordEncoder.matches(password, userDto.getClientPassword())) {
                ...
                return token;
        } else if (userDto == null) {
                errorMsseage = "계정이 존재하지 않습니다.";
        } else {
                errorMsseage = "비밀번호가 일치하지 않습니다.";
        }
```

2023-11-05 21:35 UTC, f-lab-jason commented on src/main/java/com/herryboro/order66/security/AuthProvider.java
> +        UsernamePasswordAuthenticationToken token;
요건 아래 if문 안에서만 쓰이는걸로 보이는데 여기 있을 필요가 없어보이니 아래로 옮겨주시겠어요?

2023-11-05 21:35 UTC, f-lab-jason commented on src/main/java/com/herryboro/order66/security/AuthProvider.java
> +    public Authentication authenticate(Authentication authentication) throws AuthenticationException {
여기 로직 전체가 조금 더 읽기 편하면 좋겠어요.
```
public Authentication authenticate(Authentication authentication) throws AuthenticationException {
    String userId = (String) authentication.getPrincipal();
    ClientMemberDTO userDto = clientService.getUserByClientId(userId);

    if (userDto == null) {
        throw new BadCredentialsException("계정이 존재하지 않습니다.");
    }

    String password = (String) authentication.getCredentials();
    PasswordEncoder passwordEncoder = clientService.passwordEncoder();

    if (passwordEncoder.matches(password, userDto.getClientPassword())) {
        throw new BadCredentialsException("비밀번호가 일치하지 않습니다.");
    }

    List<GrantedAuthority> roles = new ArrayList<>();
    roles.add(new SimpleGrantedAuthority("USER")); // 권한 부여

    return new UsernamePasswordAuthenticationToken(userDto.getId(), null, roles);;
}
```

2023-11-05 21:35 UTC, f-lab-jason commented on src/main/java/com/herryboro/order66/security/JwtFilter.java
> +        logger.info("==========");
이거랑 L38은 필요한건가요?

2023-11-05 21:35 UTC, f-lab-jason commented on src/main/java/com/herryboro/order66/security/TokenProvider.java
> +        System.out.println("authorities = " + authorities);;
이것도 제거해주세요 :)

2023-11-06 07:40 UTC, f-lab-jason commented
아 그리고 로직 전체에서 `client`, `user`, `member`가 혼용되어있는데 정리해서 통일하면 좋겠어요.

2023-11-16 13:50 UTC, herryboro commented on src/main/java/com/herryboro/order66/controller/ClientMemberController.java
> +    public ResponseEntity<String> mainHome() {
네. 이 /home 쪽은 spring security session + role에 따른 접근 가능/ 불가능을 테스트하기 위한 임의 코드입니다.
추 후에는 등록된 매장 list 등의 완전히 다른 코드가 들어가 예정입니다.

2023-11-16 14:02 UTC, herryboro commented on src/main/java/com/herryboro/order66/controller/ClientMemberController.java
>          }
에러 메시지를 받아서 클라이언트에 넘겨주는 예외 처리 구조를 가지고 있는 경우 공통의 ErrorUtil 클래스를 통해 할 수 있도록 구성했습니다.<br>

![ErrorUtil 코드](https://github.com/f-lab-edu/order66/assets/59191780/d561f341-6cfc-4838-89f4-da1a7ee3c927)
![ErrorUtil 코드 적용](https://github.com/f-lab-edu/order66/assets/59191780/fdf780eb-c94f-471b-9611-207ae836de10)

2023-11-16 14:08 UTC, herryboro commented on src/main/java/com/herryboro/order66/controller/ClientMemberController.java
> +    @ExceptionHandler({ClientInputDataException.class})
ClientInputDataException, passwordmismatchexception에 대한 ExceptionHandler를 InvalidInputException 하나로 만들었습니다. 멘토님이 의도하신 부분이 이것이 맞는지 모르겠습니다<br>
![exceptionHandler 처리](https://github.com/f-lab-edu/order66/assets/59191780/b63c7068-6d48-40c6-9818-cd80e658d0a3)

2023-11-16 14:22 UTC, herryboro commented on src/main/java/com/herryboro/order66/security/AuthProvider.java
> +    public Authentication authenticate(Authentication authentication) throws AuthenticationException {
@Override
    public Authentication authenticate(Authentication authentication) throws AuthenticationException {
        String id = (String) authentication.getPrincipal();
        ClientInfoDTO user = clientService.getUserByClientId(id);
        UsernamePasswordAuthenticationToken token;

        if (user == null) {
            throw new BadCredentialsException("계정이 존재하지 않습니다.");
        }

        String password = (String) authentication.getCredentials();

        if (!passwordEncoder.matches(password, user.getClientPassword())) {
            throw new BadCredentialsException("비밀번호가 일치하지 않습니다.");
        } else {
            List<GrantedAuthority> roles = new ArrayList<>();
            roles.add(new SimpleGrantedAuthority("ROLE_CLIENT")); // 권한 부여

            // 인증된 user 정보를 담아 SecurityContextHolder에 저장되는 token
            token = new UsernamePasswordAuthenticationToken(user.getId(), null, roles);
            return token;
        }
    }

이렇게 코드를 수정했습니다. 
1. 먼저 user의 존재 유무를 먼저 check하는 로직
2. 비밀번호가 일치하는지
3. 이후 권한 등록

2023-11-16 14:22 UTC, herryboro commented on src/main/java/com/herryboro/order66/controller/ClientMemberController.java
> +@RequestMapping(value = "/client")
/clients로 수정했습니다.

2023-11-16 14:23 UTC, herryboro commented on src/main/java/com/herryboro/order66/controller/JwtAuthenticationController.java
> +        System.out.println("jwt = " + jwt);
넵 미처 확인을 못한 코드였네요;

2023-12-03 04:27 UTC, f-lab-jason approved these changes

2023-12-05 00:10 UTC, merged